/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedTeacherRouteRouteImport } from './routes/_authenticated/_teacher/route'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/_student/route'
import { Route as AuthenticatedDirectorRouteRouteImport } from './routes/_authenticated/_director/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedLearnersIndexRouteImport } from './routes/_authenticated/learners.index'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/_teacher/index'
import { Route as AuthenticatedLearnersIdRouteImport } from './routes/_authenticated/learners.$id'
import { Route as AuthenticatedDirectorFacultyRouteImport } from './routes/_authenticated/_director/faculty'
import { Route as AuthenticatedDirectorAnecdotalRouteImport } from './routes/_authenticated/_director/anecdotal'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/_admin/teachers'
import { Route as AuthenticatedAdminSeedFacultyRouteImport } from './routes/_authenticated/_admin/seed-faculty'
import { Route as AuthenticatedAdminSchoolYearsRouteImport } from './routes/_authenticated/_admin/school-years'
import { Route as AuthenticatedAdminKioskRouteImport } from './routes/_authenticated/_admin/kiosk'
import { Route as AuthenticatedAdminImportLearnersRouteImport } from './routes/_authenticated/_admin/import-learners'
import { Route as AuthenticatedAdminFaceRegistrationRouteImport } from './routes/_authenticated/_admin/face-registration'
import { Route as AuthenticatedTeacherMyDllsIndexRouteImport } from './routes/_authenticated/_teacher/my-dlls.index'
import { Route as AuthenticatedDirectorDllIndexRouteImport } from './routes/_authenticated/_director/dll.index'
import { Route as AuthenticatedTeacherSectionsIdRouteImport } from './routes/_authenticated/_teacher/sections.$id'
import { Route as AuthenticatedTeacherMyDllsIdRouteImport } from './routes/_authenticated/_teacher/my-dlls.$id'
import { Route as AuthenticatedTeacherDllNewRouteImport } from './routes/_authenticated/_teacher/dll.new'
import { Route as AuthenticatedStudentStudentsMeRouteImport } from './routes/_authenticated/_student/students.me'
import { Route as AuthenticatedDirectorDllIdRouteImport } from './routes/_authenticated/_director/dll.$id'
import { Route as AuthenticatedStudentStudentsIdIndexRouteImport } from './routes/_authenticated/_student/students.$id.index'
import { Route as AuthenticatedTeacherStudentsIdAnecdotalRouteImport } from './routes/_authenticated/_teacher/students.$id.anecdotal'
import { Route as AuthenticatedTeacherSectionsIdKioskRouteImport } from './routes/_authenticated/_teacher/sections.$id.kiosk'
import { Route as AuthenticatedTeacherSectionsIdAttendanceRouteImport } from './routes/_authenticated/_teacher/sections.$id.attendance'
import { Route as AuthenticatedStudentStudentsIdAttendanceRouteImport } from './routes/_authenticated/_student/students.$id.attendance'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRouteRoute =
  AuthenticatedTeacherRouteRouteImport.update({
    id: '/_teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/_student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectorRouteRoute =
  AuthenticatedDirectorRouteRouteImport.update({
    id: '/_director',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnersIndexRoute =
  AuthenticatedLearnersIndexRouteImport.update({
    id: '/learners/',
    path: '/learners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedLearnersIdRoute = AuthenticatedLearnersIdRouteImport.update({
  id: '/learners/$id',
  path: '/learners/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectorFacultyRoute =
  AuthenticatedDirectorFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => AuthenticatedDirectorRouteRoute,
  } as any)
const AuthenticatedDirectorAnecdotalRoute =
  AuthenticatedDirectorAnecdotalRouteImport.update({
    id: '/anecdotal',
    path: '/anecdotal',
    getParentRoute: () => AuthenticatedDirectorRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeedFacultyRoute =
  AuthenticatedAdminSeedFacultyRouteImport.update({
    id: '/seed-faculty',
    path: '/seed-faculty',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSchoolYearsRoute =
  AuthenticatedAdminSchoolYearsRouteImport.update({
    id: '/school-years',
    path: '/school-years',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKioskRoute = AuthenticatedAdminKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminImportLearnersRoute =
  AuthenticatedAdminImportLearnersRouteImport.update({
    id: '/import-learners',
    path: '/import-learners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaceRegistrationRoute =
  AuthenticatedAdminFaceRegistrationRouteImport.update({
    id: '/face-registration',
    path: '/face-registration',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedTeacherMyDllsIndexRoute =
  AuthenticatedTeacherMyDllsIndexRouteImport.update({
    id: '/my-dlls/',
    path: '/my-dlls/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedDirectorDllIndexRoute =
  AuthenticatedDirectorDllIndexRouteImport.update({
    id: '/dll/',
    path: '/dll/',
    getParentRoute: () => AuthenticatedDirectorRouteRoute,
  } as any)
const AuthenticatedTeacherSectionsIdRoute =
  AuthenticatedTeacherSectionsIdRouteImport.update({
    id: '/sections/$id',
    path: '/sections/$id',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherMyDllsIdRoute =
  AuthenticatedTeacherMyDllsIdRouteImport.update({
    id: '/my-dlls/$id',
    path: '/my-dlls/$id',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherDllNewRoute =
  AuthenticatedTeacherDllNewRouteImport.update({
    id: '/dll/new',
    path: '/dll/new',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentStudentsMeRoute =
  AuthenticatedStudentStudentsMeRouteImport.update({
    id: '/students/me',
    path: '/students/me',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedDirectorDllIdRoute =
  AuthenticatedDirectorDllIdRouteImport.update({
    id: '/dll/$id',
    path: '/dll/$id',
    getParentRoute: () => AuthenticatedDirectorRouteRoute,
  } as any)
const AuthenticatedStudentStudentsIdIndexRoute =
  AuthenticatedStudentStudentsIdIndexRouteImport.update({
    id: '/students/$id/',
    path: '/students/$id/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedTeacherStudentsIdAnecdotalRoute =
  AuthenticatedTeacherStudentsIdAnecdotalRouteImport.update({
    id: '/students/$id/anecdotal',
    path: '/students/$id/anecdotal',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherSectionsIdKioskRoute =
  AuthenticatedTeacherSectionsIdKioskRouteImport.update({
    id: '/kiosk',
    path: '/kiosk',
    getParentRoute: () => AuthenticatedTeacherSectionsIdRoute,
  } as any)
const AuthenticatedTeacherSectionsIdAttendanceRoute =
  AuthenticatedTeacherSectionsIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedTeacherSectionsIdRoute,
  } as any)
const AuthenticatedStudentStudentsIdAttendanceRoute =
  AuthenticatedStudentStudentsIdAttendanceRouteImport.update({
    id: '/students/$id/attendance',
    path: '/students/$id/attendance',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedTeacherIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/face-registration': typeof AuthenticatedAdminFaceRegistrationRoute
  '/import-learners': typeof AuthenticatedAdminImportLearnersRoute
  '/kiosk': typeof AuthenticatedAdminKioskRoute
  '/school-years': typeof AuthenticatedAdminSchoolYearsRoute
  '/seed-faculty': typeof AuthenticatedAdminSeedFacultyRoute
  '/teachers': typeof AuthenticatedAdminTeachersRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/anecdotal': typeof AuthenticatedDirectorAnecdotalRoute
  '/faculty': typeof AuthenticatedDirectorFacultyRoute
  '/learners/$id': typeof AuthenticatedLearnersIdRoute
  '/learners/': typeof AuthenticatedLearnersIndexRoute
  '/dll/$id': typeof AuthenticatedDirectorDllIdRoute
  '/students/me': typeof AuthenticatedStudentStudentsMeRoute
  '/dll/new': typeof AuthenticatedTeacherDllNewRoute
  '/my-dlls/$id': typeof AuthenticatedTeacherMyDllsIdRoute
  '/sections/$id': typeof AuthenticatedTeacherSectionsIdRouteWithChildren
  '/dll/': typeof AuthenticatedDirectorDllIndexRoute
  '/my-dlls/': typeof AuthenticatedTeacherMyDllsIndexRoute
  '/students/$id/attendance': typeof AuthenticatedStudentStudentsIdAttendanceRoute
  '/sections/$id/attendance': typeof AuthenticatedTeacherSectionsIdAttendanceRoute
  '/sections/$id/kiosk': typeof AuthenticatedTeacherSectionsIdKioskRoute
  '/students/$id/anecdotal': typeof AuthenticatedTeacherStudentsIdAnecdotalRoute
  '/students/$id/': typeof AuthenticatedStudentStudentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedTeacherIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/face-registration': typeof AuthenticatedAdminFaceRegistrationRoute
  '/import-learners': typeof AuthenticatedAdminImportLearnersRoute
  '/kiosk': typeof AuthenticatedAdminKioskRoute
  '/school-years': typeof AuthenticatedAdminSchoolYearsRoute
  '/seed-faculty': typeof AuthenticatedAdminSeedFacultyRoute
  '/teachers': typeof AuthenticatedAdminTeachersRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/anecdotal': typeof AuthenticatedDirectorAnecdotalRoute
  '/faculty': typeof AuthenticatedDirectorFacultyRoute
  '/learners/$id': typeof AuthenticatedLearnersIdRoute
  '/learners': typeof AuthenticatedLearnersIndexRoute
  '/dll/$id': typeof AuthenticatedDirectorDllIdRoute
  '/students/me': typeof AuthenticatedStudentStudentsMeRoute
  '/dll/new': typeof AuthenticatedTeacherDllNewRoute
  '/my-dlls/$id': typeof AuthenticatedTeacherMyDllsIdRoute
  '/sections/$id': typeof AuthenticatedTeacherSectionsIdRouteWithChildren
  '/dll': typeof AuthenticatedDirectorDllIndexRoute
  '/my-dlls': typeof AuthenticatedTeacherMyDllsIndexRoute
  '/students/$id/attendance': typeof AuthenticatedStudentStudentsIdAttendanceRoute
  '/sections/$id/attendance': typeof AuthenticatedTeacherSectionsIdAttendanceRoute
  '/sections/$id/kiosk': typeof AuthenticatedTeacherSectionsIdKioskRoute
  '/students/$id/anecdotal': typeof AuthenticatedTeacherStudentsIdAnecdotalRoute
  '/students/$id': typeof AuthenticatedStudentStudentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_director': typeof AuthenticatedDirectorRouteRouteWithChildren
  '/_authenticated/_student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/_teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/_authenticated/_admin/face-registration': typeof AuthenticatedAdminFaceRegistrationRoute
  '/_authenticated/_admin/import-learners': typeof AuthenticatedAdminImportLearnersRoute
  '/_authenticated/_admin/kiosk': typeof AuthenticatedAdminKioskRoute
  '/_authenticated/_admin/school-years': typeof AuthenticatedAdminSchoolYearsRoute
  '/_authenticated/_admin/seed-faculty': typeof AuthenticatedAdminSeedFacultyRoute
  '/_authenticated/_admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/_director/anecdotal': typeof AuthenticatedDirectorAnecdotalRoute
  '/_authenticated/_director/faculty': typeof AuthenticatedDirectorFacultyRoute
  '/_authenticated/learners/$id': typeof AuthenticatedLearnersIdRoute
  '/_authenticated/_teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/learners/': typeof AuthenticatedLearnersIndexRoute
  '/_authenticated/_director/dll/$id': typeof AuthenticatedDirectorDllIdRoute
  '/_authenticated/_student/students/me': typeof AuthenticatedStudentStudentsMeRoute
  '/_authenticated/_teacher/dll/new': typeof AuthenticatedTeacherDllNewRoute
  '/_authenticated/_teacher/my-dlls/$id': typeof AuthenticatedTeacherMyDllsIdRoute
  '/_authenticated/_teacher/sections/$id': typeof AuthenticatedTeacherSectionsIdRouteWithChildren
  '/_authenticated/_director/dll/': typeof AuthenticatedDirectorDllIndexRoute
  '/_authenticated/_teacher/my-dlls/': typeof AuthenticatedTeacherMyDllsIndexRoute
  '/_authenticated/_student/students/$id/attendance': typeof AuthenticatedStudentStudentsIdAttendanceRoute
  '/_authenticated/_teacher/sections/$id/attendance': typeof AuthenticatedTeacherSectionsIdAttendanceRoute
  '/_authenticated/_teacher/sections/$id/kiosk': typeof AuthenticatedTeacherSectionsIdKioskRoute
  '/_authenticated/_teacher/students/$id/anecdotal': typeof AuthenticatedTeacherStudentsIdAnecdotalRoute
  '/_authenticated/_student/students/$id/': typeof AuthenticatedStudentStudentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unauthorized'
    | '/face-registration'
    | '/import-learners'
    | '/kiosk'
    | '/school-years'
    | '/seed-faculty'
    | '/teachers'
    | '/users'
    | '/anecdotal'
    | '/faculty'
    | '/learners/$id'
    | '/learners/'
    | '/dll/$id'
    | '/students/me'
    | '/dll/new'
    | '/my-dlls/$id'
    | '/sections/$id'
    | '/dll/'
    | '/my-dlls/'
    | '/students/$id/attendance'
    | '/sections/$id/attendance'
    | '/sections/$id/kiosk'
    | '/students/$id/anecdotal'
    | '/students/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/unauthorized'
    | '/face-registration'
    | '/import-learners'
    | '/kiosk'
    | '/school-years'
    | '/seed-faculty'
    | '/teachers'
    | '/users'
    | '/anecdotal'
    | '/faculty'
    | '/learners/$id'
    | '/learners'
    | '/dll/$id'
    | '/students/me'
    | '/dll/new'
    | '/my-dlls/$id'
    | '/sections/$id'
    | '/dll'
    | '/my-dlls'
    | '/students/$id/attendance'
    | '/sections/$id/attendance'
    | '/sections/$id/kiosk'
    | '/students/$id/anecdotal'
    | '/students/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/unauthorized'
    | '/_authenticated/_admin'
    | '/_authenticated/_director'
    | '/_authenticated/_student'
    | '/_authenticated/_teacher'
    | '/_authenticated/_admin/face-registration'
    | '/_authenticated/_admin/import-learners'
    | '/_authenticated/_admin/kiosk'
    | '/_authenticated/_admin/school-years'
    | '/_authenticated/_admin/seed-faculty'
    | '/_authenticated/_admin/teachers'
    | '/_authenticated/_admin/users'
    | '/_authenticated/_director/anecdotal'
    | '/_authenticated/_director/faculty'
    | '/_authenticated/learners/$id'
    | '/_authenticated/_teacher/'
    | '/_authenticated/learners/'
    | '/_authenticated/_director/dll/$id'
    | '/_authenticated/_student/students/me'
    | '/_authenticated/_teacher/dll/new'
    | '/_authenticated/_teacher/my-dlls/$id'
    | '/_authenticated/_teacher/sections/$id'
    | '/_authenticated/_director/dll/'
    | '/_authenticated/_teacher/my-dlls/'
    | '/_authenticated/_student/students/$id/attendance'
    | '/_authenticated/_teacher/sections/$id/attendance'
    | '/_authenticated/_teacher/sections/$id/kiosk'
    | '/_authenticated/_teacher/students/$id/anecdotal'
    | '/_authenticated/_student/students/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_teacher': {
      id: '/_authenticated/_teacher'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTeacherRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_director': {
      id: '/_authenticated/_director'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDirectorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners/': {
      id: '/_authenticated/learners/'
      path: '/learners'
      fullPath: '/learners/'
      preLoaderRoute: typeof AuthenticatedLearnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_teacher/': {
      id: '/_authenticated/_teacher/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/learners/$id': {
      id: '/_authenticated/learners/$id'
      path: '/learners/$id'
      fullPath: '/learners/$id'
      preLoaderRoute: typeof AuthenticatedLearnersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_director/faculty': {
      id: '/_authenticated/_director/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AuthenticatedDirectorFacultyRouteImport
      parentRoute: typeof AuthenticatedDirectorRouteRoute
    }
    '/_authenticated/_director/anecdotal': {
      id: '/_authenticated/_director/anecdotal'
      path: '/anecdotal'
      fullPath: '/anecdotal'
      preLoaderRoute: typeof AuthenticatedDirectorAnecdotalRouteImport
      parentRoute: typeof AuthenticatedDirectorRouteRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/teachers': {
      id: '/_authenticated/_admin/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/seed-faculty': {
      id: '/_authenticated/_admin/seed-faculty'
      path: '/seed-faculty'
      fullPath: '/seed-faculty'
      preLoaderRoute: typeof AuthenticatedAdminSeedFacultyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/school-years': {
      id: '/_authenticated/_admin/school-years'
      path: '/school-years'
      fullPath: '/school-years'
      preLoaderRoute: typeof AuthenticatedAdminSchoolYearsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/kiosk': {
      id: '/_authenticated/_admin/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AuthenticatedAdminKioskRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/import-learners': {
      id: '/_authenticated/_admin/import-learners'
      path: '/import-learners'
      fullPath: '/import-learners'
      preLoaderRoute: typeof AuthenticatedAdminImportLearnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/face-registration': {
      id: '/_authenticated/_admin/face-registration'
      path: '/face-registration'
      fullPath: '/face-registration'
      preLoaderRoute: typeof AuthenticatedAdminFaceRegistrationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_teacher/my-dlls/': {
      id: '/_authenticated/_teacher/my-dlls/'
      path: '/my-dlls'
      fullPath: '/my-dlls/'
      preLoaderRoute: typeof AuthenticatedTeacherMyDllsIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/_director/dll/': {
      id: '/_authenticated/_director/dll/'
      path: '/dll'
      fullPath: '/dll/'
      preLoaderRoute: typeof AuthenticatedDirectorDllIndexRouteImport
      parentRoute: typeof AuthenticatedDirectorRouteRoute
    }
    '/_authenticated/_teacher/sections/$id': {
      id: '/_authenticated/_teacher/sections/$id'
      path: '/sections/$id'
      fullPath: '/sections/$id'
      preLoaderRoute: typeof AuthenticatedTeacherSectionsIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/_teacher/my-dlls/$id': {
      id: '/_authenticated/_teacher/my-dlls/$id'
      path: '/my-dlls/$id'
      fullPath: '/my-dlls/$id'
      preLoaderRoute: typeof AuthenticatedTeacherMyDllsIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/_teacher/dll/new': {
      id: '/_authenticated/_teacher/dll/new'
      path: '/dll/new'
      fullPath: '/dll/new'
      preLoaderRoute: typeof AuthenticatedTeacherDllNewRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/_student/students/me': {
      id: '/_authenticated/_student/students/me'
      path: '/students/me'
      fullPath: '/students/me'
      preLoaderRoute: typeof AuthenticatedStudentStudentsMeRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_director/dll/$id': {
      id: '/_authenticated/_director/dll/$id'
      path: '/dll/$id'
      fullPath: '/dll/$id'
      preLoaderRoute: typeof AuthenticatedDirectorDllIdRouteImport
      parentRoute: typeof AuthenticatedDirectorRouteRoute
    }
    '/_authenticated/_student/students/$id/': {
      id: '/_authenticated/_student/students/$id/'
      path: '/students/$id'
      fullPath: '/students/$id/'
      preLoaderRoute: typeof AuthenticatedStudentStudentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_teacher/students/$id/anecdotal': {
      id: '/_authenticated/_teacher/students/$id/anecdotal'
      path: '/students/$id/anecdotal'
      fullPath: '/students/$id/anecdotal'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIdAnecdotalRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/_teacher/sections/$id/kiosk': {
      id: '/_authenticated/_teacher/sections/$id/kiosk'
      path: '/kiosk'
      fullPath: '/sections/$id/kiosk'
      preLoaderRoute: typeof AuthenticatedTeacherSectionsIdKioskRouteImport
      parentRoute: typeof AuthenticatedTeacherSectionsIdRoute
    }
    '/_authenticated/_teacher/sections/$id/attendance': {
      id: '/_authenticated/_teacher/sections/$id/attendance'
      path: '/attendance'
      fullPath: '/sections/$id/attendance'
      preLoaderRoute: typeof AuthenticatedTeacherSectionsIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedTeacherSectionsIdRoute
    }
    '/_authenticated/_student/students/$id/attendance': {
      id: '/_authenticated/_student/students/$id/attendance'
      path: '/students/$id/attendance'
      fullPath: '/students/$id/attendance'
      preLoaderRoute: typeof AuthenticatedStudentStudentsIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminFaceRegistrationRoute: typeof AuthenticatedAdminFaceRegistrationRoute
  AuthenticatedAdminImportLearnersRoute: typeof AuthenticatedAdminImportLearnersRoute
  AuthenticatedAdminKioskRoute: typeof AuthenticatedAdminKioskRoute
  AuthenticatedAdminSchoolYearsRoute: typeof AuthenticatedAdminSchoolYearsRoute
  AuthenticatedAdminSeedFacultyRoute: typeof AuthenticatedAdminSeedFacultyRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminFaceRegistrationRoute:
      AuthenticatedAdminFaceRegistrationRoute,
    AuthenticatedAdminImportLearnersRoute:
      AuthenticatedAdminImportLearnersRoute,
    AuthenticatedAdminKioskRoute: AuthenticatedAdminKioskRoute,
    AuthenticatedAdminSchoolYearsRoute: AuthenticatedAdminSchoolYearsRoute,
    AuthenticatedAdminSeedFacultyRoute: AuthenticatedAdminSeedFacultyRoute,
    AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDirectorRouteRouteChildren {
  AuthenticatedDirectorAnecdotalRoute: typeof AuthenticatedDirectorAnecdotalRoute
  AuthenticatedDirectorFacultyRoute: typeof AuthenticatedDirectorFacultyRoute
  AuthenticatedDirectorDllIdRoute: typeof AuthenticatedDirectorDllIdRoute
  AuthenticatedDirectorDllIndexRoute: typeof AuthenticatedDirectorDllIndexRoute
}

const AuthenticatedDirectorRouteRouteChildren: AuthenticatedDirectorRouteRouteChildren =
  {
    AuthenticatedDirectorAnecdotalRoute: AuthenticatedDirectorAnecdotalRoute,
    AuthenticatedDirectorFacultyRoute: AuthenticatedDirectorFacultyRoute,
    AuthenticatedDirectorDllIdRoute: AuthenticatedDirectorDllIdRoute,
    AuthenticatedDirectorDllIndexRoute: AuthenticatedDirectorDllIndexRoute,
  }

const AuthenticatedDirectorRouteRouteWithChildren =
  AuthenticatedDirectorRouteRoute._addFileChildren(
    AuthenticatedDirectorRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentStudentsMeRoute: typeof AuthenticatedStudentStudentsMeRoute
  AuthenticatedStudentStudentsIdAttendanceRoute: typeof AuthenticatedStudentStudentsIdAttendanceRoute
  AuthenticatedStudentStudentsIdIndexRoute: typeof AuthenticatedStudentStudentsIdIndexRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentStudentsMeRoute: AuthenticatedStudentStudentsMeRoute,
    AuthenticatedStudentStudentsIdAttendanceRoute:
      AuthenticatedStudentStudentsIdAttendanceRoute,
    AuthenticatedStudentStudentsIdIndexRoute:
      AuthenticatedStudentStudentsIdIndexRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedTeacherSectionsIdRouteChildren {
  AuthenticatedTeacherSectionsIdAttendanceRoute: typeof AuthenticatedTeacherSectionsIdAttendanceRoute
  AuthenticatedTeacherSectionsIdKioskRoute: typeof AuthenticatedTeacherSectionsIdKioskRoute
}

const AuthenticatedTeacherSectionsIdRouteChildren: AuthenticatedTeacherSectionsIdRouteChildren =
  {
    AuthenticatedTeacherSectionsIdAttendanceRoute:
      AuthenticatedTeacherSectionsIdAttendanceRoute,
    AuthenticatedTeacherSectionsIdKioskRoute:
      AuthenticatedTeacherSectionsIdKioskRoute,
  }

const AuthenticatedTeacherSectionsIdRouteWithChildren =
  AuthenticatedTeacherSectionsIdRoute._addFileChildren(
    AuthenticatedTeacherSectionsIdRouteChildren,
  )

interface AuthenticatedTeacherRouteRouteChildren {
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherDllNewRoute: typeof AuthenticatedTeacherDllNewRoute
  AuthenticatedTeacherMyDllsIdRoute: typeof AuthenticatedTeacherMyDllsIdRoute
  AuthenticatedTeacherSectionsIdRoute: typeof AuthenticatedTeacherSectionsIdRouteWithChildren
  AuthenticatedTeacherMyDllsIndexRoute: typeof AuthenticatedTeacherMyDllsIndexRoute
  AuthenticatedTeacherStudentsIdAnecdotalRoute: typeof AuthenticatedTeacherStudentsIdAnecdotalRoute
}

const AuthenticatedTeacherRouteRouteChildren: AuthenticatedTeacherRouteRouteChildren =
  {
    AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
    AuthenticatedTeacherDllNewRoute: AuthenticatedTeacherDllNewRoute,
    AuthenticatedTeacherMyDllsIdRoute: AuthenticatedTeacherMyDllsIdRoute,
    AuthenticatedTeacherSectionsIdRoute:
      AuthenticatedTeacherSectionsIdRouteWithChildren,
    AuthenticatedTeacherMyDllsIndexRoute: AuthenticatedTeacherMyDllsIndexRoute,
    AuthenticatedTeacherStudentsIdAnecdotalRoute:
      AuthenticatedTeacherStudentsIdAnecdotalRoute,
  }

const AuthenticatedTeacherRouteRouteWithChildren =
  AuthenticatedTeacherRouteRoute._addFileChildren(
    AuthenticatedTeacherRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDirectorRouteRoute: typeof AuthenticatedDirectorRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedTeacherRouteRoute: typeof AuthenticatedTeacherRouteRouteWithChildren
  AuthenticatedLearnersIdRoute: typeof AuthenticatedLearnersIdRoute
  AuthenticatedLearnersIndexRoute: typeof AuthenticatedLearnersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDirectorRouteRoute: AuthenticatedDirectorRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedTeacherRouteRoute: AuthenticatedTeacherRouteRouteWithChildren,
  AuthenticatedLearnersIdRoute: AuthenticatedLearnersIdRoute,
  AuthenticatedLearnersIndexRoute: AuthenticatedLearnersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
