
ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS am_time_in  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS am_time_out TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS pm_time_in  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS pm_time_out TIMESTAMPTZ;
